### ISSUE TITLE
Emulator App

### ISSUE THREAD

**Issue by cagnulein** [ajchellew/zwiftplay#2]
Hi @ajchellew thanks for your amazing work!
I'm testing the emulator app, it builds fine but it seems that it doesn't start the advertisment correctly on android 14. On which android version did you test it?
Thanks!

I'm about to implement your code in C++ in my project https://github.com/cagnulein/qdomyos-zwift/issues/1984

**Comment by cagnulein** [comment]
ah I just saw this https://github.com/ajchellew/zwiftplay/commit/1c6595be778d55a8633692bc1f230190ebd04f7e :)

**Comment by ajchellew** [comment]
@cagnulein yeah, I had ambitions beyond what was possible with Android, theoretically I could have made an emulated controller that could talk to the app I'd made and ignore the standard BLE services but I didn't feel that would achieve much.

I tried to switch over to using a Pi Pico but once I learned how to turn off the default services in MicroPython I still couldn't actually add as many services as the Zwift Play controller presents. So that is also parked. 

Hopefully the code here has been of use to you.

**Comment by cagnulein** [comment]
yeah it's very useful, thanks! i thought to implement the zwift play
without buying them but at the end i will definitely buy them since i can't
use this emulator :)

have a nice weekend!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 12 gen 2024 alle 19:29 ajchellew ***@***.***>
ha scritto:

**Comment by sheitmaster** [comment]
If you get this or a windows app working i would be SO happy, Wahoo just pushed an update to the kickr core that adds support for virtual shifting, and i don't want to buy the play controllers.

**Comment by ajchellew** [comment]
@sheitmaster as an owner of both the Kickr Core and the Play controllers can you point me to more on this? Nothing I can find on wahoo or blog sites

**Comment by sheitmaster** [comment]
KICKR CORE Firmware v1.3.17 - 22 January 2024
Updated: optimizations and general improvements

Wahoo doesn't actually say, but this update is in preparation for zwift play, the kickr core is ready, but the code also has to be implemented by zwift.

The author of the GTA bike mod for gta5 came across it as it started to crash the mod and he investigated further.

**Comment by ajchellew** [comment]
@sheitmaster can you point me to your source? I'm familiar with Makinolo, his blog helped me with this project but I can't see anything new.

I don't see how the Kickr Core can be updated to have virtual shifting without the 'cog' the new Zwift trainer has. Unless there's a retrofit cog coming...

**Comment by sheitmaster** [comment]
You don't need the cog.
The reason they sell the cog is just to make it simple for people and earn more money, you can use whatever gear you want and virtual shift on that.
Just select big ring and the cog that makes the chainline straight.
The source is makinolo post on the facebook page for the mod, and GP-lama's reddit.

**Comment by ajchellew** [comment]
Reddit post suggests the ZAP BLE service has appeared on the Core, I'll update my Core over the weekend and snoop the data, I'm guessing there's more posted on Facebook already as I don't really understand the assumption on the r/zwift Reddit post. Seems to suggest the Core is becoming a Play controller itself. No indication other than the BLE service and characteristics.

**Comment by sheitmaster** [comment]
Yeah reddit is a mess on the best of days.
But wahoo has stated previously that they are adding virtual shifting, but never said wich models would get it, i always assumed it would be for the most expensive ones, but i think they do this as a way to keep people buying their entry level models instead of switching to zwift hub.

**Comment by ajchellew** [comment]
Updating the Core does indeed gain: 

```
Unknown Service (00000001-19ca-4651-86e5-fa29dcdd09d1)
- Unknown Characteristic [N] (00000002-19ca-4651-86e5-fa29dcdd09d1)
   Client Characteristic Configuration (0x2902)
- Unknown Characteristic [WNR] (00000003-19ca-4651-86e5-fa29dcdd09d1)
- Unknown Characteristic [I] (00000004-19ca-4651-86e5-fa29dcdd09d1)
```

[Corresponding to the UUIDs in the custom service](https://github.com/ajchellew/zwiftplay/blob/125796df738a4cd518f1ba71d568696d4a309c3a/zaplibrary/src/main/java/com/che/zap/device/ZapBleUuids.kt#L12C84-L12C96)

This service functions as a virtual serial port over BLE and carries Protocol Buffer encoded data. The data types can be found in the code, there is a `ControllerNotification` type for the Zwift Play controllers but many other types such as `TrainerConfigStatus` `TrainerMode` `RoadFeelPreset` so was pretty clear the custom Zwift service is not just for the Play controllers, (my assumption is ZAP stands for Zwift Accessory Protocol, this protocol is way over-engineered for just a Bluetooth HID anyway) 

There are other 'Brevet' devices that have this protocol, unsurprisingly one is the Zwift Hub based on all the `Hub*` types
```
RC1 // Zwift Play controllers
ST3 // Hub
BC1 // "ZC" ? Zwift Click?
SF2 // "ZF"  ?
```
Worth noting the current Android companion app doesn't know of a new devices since I did this work initially.

My guess is Zwift will talk to the Kickr Core over this service in future but I don't know if you can say its definitely for virtual shifting and I definitely wouldn't think the Zwift Play will connect to it directly. But you would probably right, there might not be an onscreen button when you could buy the Zwift Play controllers...

If that comes to Zwift I'll see about reverse engineering it as most of the work is done getting the protocol decoded. It would be much easier to control the trainer directly than try to emulate something to talk to the Zwift software that they could easily block.

I can't @ makinolo to come along and tell me what else he knows

**Comment by ajchellew** [comment]
Closing this issue, you can't emulate the controllers with android because:
- there's 2 of them
- you can't disable the system BLE Services that the Zwift accessories also need to use

I looked at doing this with Pi Picos, again running into the same problems, although I found with help how to disable the default services, adding as many as the controllers need breaks the advertising, that's without the need to advertise twice.

I will and have started with capturing and attempting to reverse engineer how to directly shift gears on the Kickr. but even if this is achieved it would mean if using Zwift running either without Bluetooth control or using Ant+ to the trainer.
